### PR TITLE
add !lastseen and !mail commands

### PR DESCRIPTION
**Pull request by rumly111**
Adds !mail and !lastseen commands, like it was in Auctionbot.
Uses sqlite db to store info.

### CODE REVIEW

**Comment by wushin** [comment]
Can you extract the online list url from SMSG_CHAR_MAP_INFO packet?
Also can have it grab and parse the url as soon as it logs in?

Otherwise looks great.

**Comment by rumly111** [comment]
> Also can have it grab and parse the url as soon as it logs in?
You mean validate the URL itself for being correct ?

**Comment by wushin** [comment]
No I mean enter everyone visible into last seen on login. seems like it has some start-up time before it does the last seen entries.

**Comment by rumly111** [comment]
Updating the online users list runs in a separate thread, the only way to control it is through .start() and .stop() method of corresponding classes. .start() is called as soon as you connect to mapserv. The delay shouldn't be more than few seconds, and ManaMarket isn't restarted that often.

**Comment by wushin** [comment]
ok. then I guess just placing the online url in the config section is the only change as it can vary server to server

**Comment by rumly111** [comment]
added config.online_txt_url option. Also a 0.7 second delay between messages when tradebot notifies users about incoming mails.

**Pull request closed without merging**
